import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  DATABASE_URL: Joi.string().uri().required(),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().default('24h'),
  PORT: Joi.number().default(4000),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  SMTP_HOST: Joi.string().optional().allow(''),
  SMTP_PORT: Joi.number().default(587),
  SMTP_USER: Joi.string().optional().allow(''),
  SMTP_PASS: Joi.string().optional().allow(''),
  SMTP_FROM: Joi.string().email().default('noreply@gpls.vn'),
  OPENAI_API_KEY: Joi.string().optional().allow(''),
  GEMINI_API_KEY: Joi.string().optional().allow(''),
  GOLD_API_KEY: Joi.string().optional().allow('').default(''),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  GOOGLE_CLIENT_ID: Joi.string().optional().allow(''),
  GOOGLE_CLIENT_SECRET: Joi.string().optional().allow(''),
  GOOGLE_CALLBACK_URL: Joi.string().optional().allow(''),
  WEB_URL: Joi.string().optional().allow(''),
  VAPID_PUBLIC_KEY: Joi.string().optional().allow('').default(''),
  VAPID_PRIVATE_KEY: Joi.string().optional().allow('').default(''),
  VAPID_EMAIL: Joi.string().optional().allow('').default('admin@goldplan.vn'),
});
